"""Your migration message

Revision ID: 4095cb11ebd7
Revises: 
Create Date: 2024-11-17 00:18:41.025863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4095cb11ebd7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hostel',
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('hname', sa.String(length=100), nullable=False),
    sa.Column('warden', sa.String(length=100), nullable=False),
    sa.Column('nrooms', sa.Integer(), nullable=False),
    sa.Column('nstudents', sa.Integer(), nullable=False),
    sa.Column('h_type', sa.String(length=10), nullable=False),
    sa.Column('vacant_rooms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('h_id')
    )
    op.create_table('hostel_A',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel_B',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel_C',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hostel_D',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_num')
    )
    op.create_table('hostel_E',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_num')
    )
    op.create_table('hostel_F',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h_id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=50), nullable=False),
    sa.Column('roll_num', sa.String(length=20), nullable=False),
    sa.Column('room_num', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('branch', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['h_id'], ['Hostel.h_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_num')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hostel_F')
    op.drop_table('hostel_E')
    op.drop_table('hostel_D')
    op.drop_table('hostel_C')
    op.drop_table('hostel_B')
    op.drop_table('hostel_A')
    op.drop_table('Hostel')
    # ### end Alembic commands ###
