"""hostel 5 update

Revision ID: 5b8d3a70e3fe
Revises: a550f390719c
Create Date: 2024-12-04 22:46:36.105950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8d3a70e3fe'
down_revision = 'a550f390719c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_E', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=True))
        batch_op.drop_column('branch')
        batch_op.drop_column('floor')
        batch_op.drop_column('batch')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_E', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('floor', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('branch', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    # ### end Alembic commands ###
