"""null true

Revision ID: a4c1b255dead
Revises: 4095cb11ebd7
Create Date: 2024-12-02 08:26:00.272856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c1b255dead'
down_revision = '4095cb11ebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_F', schema=None) as batch_op:
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_F', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
