"""Null is now true

Revision ID: db660d26f9d1
Revises: 5b8d3a70e3fe
Create Date: 2024-12-06 21:23:07.957254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db660d26f9d1'
down_revision = '5b8d3a70e3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Hostel', schema=None) as batch_op:
        batch_op.alter_column('hname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('hostel_A', schema=None) as batch_op:
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('hostel_B', schema=None) as batch_op:
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('hostel_C', schema=None) as batch_op:
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('hostel_D', schema=None) as batch_op:
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostel_D', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hostel_C', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hostel_B', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('hostel_A', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('batch',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('floor',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('room_num',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('roll_num',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('h_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('Hostel', schema=None) as batch_op:
        batch_op.alter_column('hname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
